# --- WORD2VEC ---
./word2vec_joint -corpus ../Data/Corpus/NYT/NYT.train -dimension 300 -word2vec 1 -word2vec-thread 12 -rcm 0 -pretrain 0 -output-model Model/NYT_WORD2VEC_R
# --- PPDB ---
./word2vec_joint -corpus ../Data/Corpus/NYT/NYT.train -dimension 300 -word2vec 1 -word2vec-thread 12 -rcm 1 -rcm-epoch 100 -rcm-lambda 0.0001 -rcm-resource ../Data/Resource/PPDB/PPDB-xxl-lexical.train -rcm-thread 1 -rcm-method 0 -pretrain 1 -pretrain-model Model/NYT_WORD2VEC_R.bin -output-model Model/PPDB_BASELINE
./word2vec_joint -corpus ../Data/Corpus/NYT/NYT.train -dimension 300 -word2vec 1 -word2vec-thread 12 -rcm 1 -rcm-epoch 100 -rcm-lambda 0.0001 -rcm-resource ../Data/Resource/PPDB/PPDB-xxl-lexical.train -rcm-thread 1 -rcm-method 1 -rcm-threshold 50 -pretrain 1 -pretrain-model Model/NYT_WORD2VEC_R.bin -output-model Model/PPDB_THRESHOLD
./word2vec_joint -corpus ../Data/Corpus/NYT/NYT.train -dimension 300 -word2vec 1 -word2vec-thread 12 -rcm 1 -rcm-epoch 100 -rcm-lambda 0.001 -rcm-resource ../Data/Resource/PPDB/PPDB-xxl-lexical.train -rcm-thread 1 -rcm-method 2 -pretrain 1 -pretrain-model Model/NYT_WORD2VEC_R.bin -output-model Model/PPDB_FREQUENCY
./word2vec_joint -corpus ../Data/Corpus/NYT/NYT.train -dimension 300 -word2vec 1 -word2vec-thread 12 -rcm 1 -rcm-epoch 100 -rcm-lambda 0.001 -rcm-resource ../Data/Resource/PPDB/PPDB-xxl-lexical.train -rcm-ic ../Data/Corpus/NYT/NYT.entropy -rcm-thread 1 -rcm-method 3 -pretrain 1 -pretrain-model Model/NYT_WORD2VEC_R.bin -output-model Model/PPDB_ENTROPY
# --- WORDNET ---
./word2vec_joint -corpus ../Data/Corpus/NYT/NYT.train -dimension 300 -word2vec 1 -word2vec-thread 12 -rcm 1 -rcm-epoch 100 -rcm-lambda 0.0001 -rcm-resource ../Data/Resource/WordNet/WordNet.Synonym.train -rcm-thread 1 -rcm-method 0 -pretrain 1 -pretrain-model Model/NYT_WORD2VEC_R.bin -output-model Model/WORDNET_BASELINE
./word2vec_joint -corpus ../Data/Corpus/NYT/NYT.train -dimension 300 -word2vec 1 -word2vec-thread 12 -rcm 1 -rcm-epoch 100 -rcm-lambda 0.0001 -rcm-resource ../Data/Resource/WordNet/WordNet.Synonym.train -rcm-thread 1 -rcm-method 1 -rcm-threshold 50 -pretrain 1 -pretrain-model Model/NYT_WORD2VEC_R.bin -output-model Model/WORDNET_THRESHOLD
./word2vec_joint -corpus ../Data/Corpus/NYT/NYT.train -dimension 300 -word2vec 1 -word2vec-thread 12 -rcm 1 -rcm-epoch 100 -rcm-lambda 0.001 -rcm-resource ../Data/Resource/WordNet/WordNet.Synonym.train -rcm-thread 1 -rcm-method 2 -pretrain 1 -pretrain-model Model/NYT_WORD2VEC_R.bin -output-model Model/WORDNET_FREQUENCY
./word2vec_joint -corpus ../Data/Corpus/NYT/NYT.train -dimension 300 -word2vec 1 -word2vec-thread 12 -rcm 1 -rcm-epoch 100 -rcm-lambda 0.001 -rcm-resource ../Data/Resource/WordNet/WordNet.Synonym.train -rcm-ic ../Data/Corpus/NYT/NYT.entropy -rcm-thread 1 -rcm-method 3 -pretrain 1 -pretrain-model Model/NYT_WORD2VEC_R.bin -output-model Model/WORDNET_ENTROPY